# Generated by Django 4.2.17 on 2025-12-23 09:38

from django.db import migrations, models
import milestones.models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='color',
            field=models.CharField(default='#8884d8', max_length=63, validators=[milestones.models.validate_hex_color]),
        ),
    ]
