# Generated by Codex for file uploader v1

import os

from django.db import migrations, models


def populate_uploaded_file_metadata(apps, schema_editor):
    UploadedFile = apps.get_model("fileuploader", "UploadedFile")
    for uploaded_file in UploadedFile.objects.all():
        changed = False
        if not uploaded_file.original_name:
            uploaded_file.original_name = os.path.basename(uploaded_file.file.name)
            changed = True
        if uploaded_file.stored_size_bytes == 0:
            try:
                uploaded_file.stored_size_bytes = uploaded_file.file.size
                changed = True
            except Exception:
                pass
        if changed:
            uploaded_file.save(
                update_fields=["original_name", "stored_size_bytes"]
            )


class Migration(migrations.Migration):
    dependencies = [
        ("fileuploader", "0003_uploaduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="original_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="stored_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploaduser",
            name="is_unlimited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="uploaduser",
            name="storage_quota_bytes",
            field=models.BigIntegerField(default=1073741824),
        ),
        migrations.RunPython(
            populate_uploaded_file_metadata,
            migrations.RunPython.noop,
        ),
    ]
