# Generated by Django 4.2.3 on 2024-03-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfys', '0006_alter_gfy_unique_together_gfy_object_id_gfy_video_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gfy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gfys.gfy')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
