# Generated by Django 4.2.3 on 2024-03-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfys', '0007_gfyview'),
    ]

    operations = [
        migrations.AddField(
            model_name='gfy',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gfy',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
