# Generated by Django 4.2.2 on 2023-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("short_id", models.CharField(max_length=20, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("accessed", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
