# Generated by Django 4.2.3 on 2024-04-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="number_of_uses",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
