# Generated by Django 4.2.17 on 2025-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_shorturl_number_of_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
