# Generated by Django 4.2.17 on 2025-03-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_alter_shorturl_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
