# Generated by Django 4.2.17 on 2025-03-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_shorturl_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='accessed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
