# Generated by Django 4.2.17 on 2025-03-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_alter_shorturl_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
