# Generated by Django 4.2.17 on 2025-03-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_alter_shorturl_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.TextField(),
        ),
    ]
