# Generated by Django 4.2.2 on 2023-07-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name="ReleaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album", models.CharField(max_length=510)),
                ("title", models.CharField(max_length=510)),
                ("release_date", models.DateField()),
                ("urls", models.JSONField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpopcomebacks.artist",
                    ),
                ),
                (
                    "release_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kpopcomebacks.releasetype",
                    ),
                ),
            ],
        ),
    ]
