# Generated by Django 4.2.2 on 2023-07-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kpopcomebacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("artist", "album", "title", "release_date")},
        ),
    ]
