# Generated by Django 4.2.2 on 2023-07-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpopcomebacks", "0002_alter_release_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="reddit_urls",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
