# Generated by Django 4.2.17 on 2026-09-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiControl',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('input_characters', models.PositiveIntegerField()),
                ('prompt_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('total_tokens', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='aicontrol',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='emojify_single_control'),
        ),
    ]
